### ISSUE TITLE
error loading async bundle when eager_loading=True

### ISSUE THREAD

**Issue by michaelbabyn** [BSd3v/dash-chart-editor#11]
If I initialize a dash app using DCE like this `app = Dash(__name__, eager_loading=True)`, I see this error
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/michael/miniconda3/envs/p43/lib/python3.10/site-packages/dash_chart_editor/async-DashChartEditor.js'
```
This is using dash-chart-editor ==0.0.1rc1 and here is a MRE:

```python
import dash_chart_editor as dce
from dash import Dash, html
import plotly.express as px


app = Dash(__name__, external_scripts=["https://cdn.plot.ly/plotly-2.18.2.min.js"], eager_loading=True)

df = px.data.gapminder()

app.layout = html.Div([
    html.H4("Dash Chart Editor Demo with the Plotly Gapminder dataset"),
    dce.DashChartEditor(
        dataSources=df.to_dict("list"),
    )
])


if __name__ == "__main__":
    app.run_server(debug=True, port=8095)
```

**Comment by BSd3v** [comment]
Please use a4, this issue may persist, but that is the latest version.

**Comment by michaelbabyn** [comment]
Oh, ok. I still see the issue with a4 (I actually tested that first but I assumed that rc1>a4 so I decided to test that do)

**Comment by BSd3v** [comment]
This isn't an async file, so it will not show. 

With eager running, is there a cutoff for file size?

**Comment by michaelbabyn** [comment]
Right, if there isn't an async file maybe it's easiest to just remove the reference to it in the _js_dist. I just created a PR that does this in https://github.com/BSd3v/dash-chart-editor/pull/13
