### ISSUE TITLE
parseChartKeys_fig fails for Scatter3d plot

### ISSUE THREAD

**Issue by JamesIsCooke** [BSd3v/dash-chart-editor#14]
parseChartKeys_fig compares chart['type'].title()  with all members of go to get the trace type. However, for a 3d scatter:
chart['type'].title() is Scatter3D (capital D) and getmembers(go, isclass)[51][0] is Scatter3d (lower case d), so it cannot find the plot type.
Suggest 
`  if i.lower() == chart['type'].lower():
            realChart = y`

**Comment by BSd3v** [comment]
Thanks for catching this, I typically dont use 3d charts. 😄

**Comment by BSd3v** [comment]
This is fixed in https://github.com/BSd3v/dash-chart-editor/commit/ace788d9e6bd51dcacf10ac5a37a03a0b6d2b3ed
