### ISSUE TITLE
Broken Trace Title...

### ISSUE THREAD

**Issue by DarkCTO** [BSd3v/dash-chart-editor#27]
![2023-10-10-162704_329x229_scrot](https://github.com/BSd3v/dash-chart-editor/assets/99158109/74f19424-1950-46f7-9c40-33b3dd54b04d)

See image...
Basically this happens if make your code more complex than the default.
Try importing a class before running your app...

**Comment by BSd3v** [comment]
This is adjustable by working with the styles.

I have a more current version that I am working on releasing where this is fixed.

**Comment by BSd3v** [comment]
I think you can fix it in the current version by doing this:

```
.editor_controls .fold__top {
    min-height: 30px !important;
}
```

**Comment by DarkCTO** [comment]
It works. You can close this issue when the update comes out.

**Comment by mito310-kc** [comment]
I have encountered the same problem. Should I clone the `dev` branch and install it instead of using pip to get the fixed version?

**Comment by BSd3v** [comment]
I just pushed a new version `a5` out, this version also contains some support for charts that werent originally included by plotly. Including indicators.

**Comment by mito310-kc** [comment]
Thank you for new version! I confirmed that this issue was fixed.
